model:
  type: "classifier"
  backbone: "efficientnet-b0"
training:
  optimizer: 
    type: "SGD"
    lr: 1.5e-2
    momentum: 0.9
    weight_decay: 1e-5
  epochs: 30
  gpu: true
  batch_size: 65
  save_best: true
  
  