model:
  type: "detection"
  backbone: "efficientdet-b0"
  fpn: "retinanet"
training:
  optimizer: 
    type: "SGD"
    lr: 1e-5
    momentum: 0.9
    weight_decay: 1e-5
  epochs: 100
  gpu: True
  train_batch_size: 40
  eval_batch_size: 25
  save_best: True
  