model:
  type: "detection"
  backbone: "efficientdet-b0"
training:
  optimizer: 
    type: "SGD"
    lr: 1e-3
    momentum: 0.9
    weight_decay: 1e-5
  epochs: 50
  gpu: True
  train_batch_size: 10
  eval_batch_size: 64
  save_best: True
  
  