model:
  type: "detection"
  backbone: "vovnet-19"
  fpn: "retinanet"
training:
  optimizer: 
    type: "SGD"
    lr: 1e-4
    momentum: 0.9
    weight_decay: 1e-5
  epochs: 30
  gpu: True
  train_batch_size: 1
  eval_batch_size: 1
  save_best: True
  